### ISSUE TITLE
False Positive on H1 Test

### ISSUE THREAD

**Issue by tedsecretsource** [SecretSourceWeb/ratify#11]
**Summary**

On some sites Ratify claims there's an issue with H1 but then lists all the heading tags found on the home page. The issue, I think, is that either the test explanation is not clear or the test itself is actually failing on some sites.

The issue manifests as the report with an X and a list of all the heading elements on the page, including 1 H1.

The attached HTML can be used as test input.

[No H1s.txt](https://github.com/SecretSourceWeb/ratify/files/4152939/No.H1s.txt)

**Comment by tedmasterweb** [comment]
Fixed by [this commit](https://github.com/SecretSourceWeb/ratify/commit/9c8629a68fcb46398b9add2bd012b07adc3a1acd)
